"""Training package primitives for Pong IA."""

from checkpoint import (
    Checkpoint,
    CheckpointNotFoundError,
    InvalidCheckpointError,
    load_checkpoint,
    save_checkpoint,
)
from export_onnx import (
    DEFAULT_OPSET_VERSION,
    InvalidOnnxParityError,
    OnnxParityResult,
    export_to_onnx,
    verify_onnx_parity,
)
from metrics import InvalidMetricsWindowError, MetricsTracker, TrainingMetrics
from model import ACTIONS, HIDDEN_DIMS, INPUT_DIM, InvalidModelInputError, PolicyForward, PongPolicyNetwork
from policy import InvalidPolicyObservationError, PolicyDecision, decide_action, make_policy_callback
from reinforce import (
    InvalidDiscountError,
    InvalidReinforceLossError,
    ReinforceUpdateResult,
    RewardFn,
    compute_reinforce_loss,
    discount_episode_rewards,
    discount_rewards,
    normalize_returns,
    run_reinforce_update,
)
from reward_shaping import (
    DEFAULT_CENTERING_REWARD_SCALE,
    DEFAULT_CENTERING_WINDOW_RATIO,
    DEFAULT_CENTER_HOLD_BONUS,
    DEFAULT_IDLE_MOVEMENT_PENALTY,
    DEFAULT_MISS_PENALTY,
    DEFAULT_REBOUND_REWARD,
    centering_reward,
    compute_batched_rebound_rewards,
    normalized_right_paddle_center_distance,
    rebound_reward,
    right_paddle_hit,
    right_paddle_miss,
    should_apply_centering_bias,
)
from rollout import EpisodeStep, InvalidRolloutError, RolloutEpisode, run_episode
from trainer import (
    BEST_CHECKPOINT_NAME,
    LATEST_CHECKPOINT_NAME,
    InvalidTrainerConfigError,
    TrainerConfig,
    TrainingRun,
    run_training,
)

__all__ = [
    "ACTIONS",
    "BEST_CHECKPOINT_NAME",
    "Checkpoint",
    "CheckpointNotFoundError",
    "DEFAULT_CENTERING_REWARD_SCALE",
    "DEFAULT_CENTERING_WINDOW_RATIO",
    "DEFAULT_CENTER_HOLD_BONUS",
    "DEFAULT_IDLE_MOVEMENT_PENALTY",
    "DEFAULT_MISS_PENALTY",
    "DEFAULT_OPSET_VERSION",
    "DEFAULT_REBOUND_REWARD",
    "EpisodeStep",
    "HIDDEN_DIMS",
    "INPUT_DIM",
    "InvalidCheckpointError",
    "InvalidDiscountError",
    "InvalidMetricsWindowError",
    "InvalidModelInputError",
    "InvalidOnnxParityError",
    "InvalidPolicyObservationError",
    "InvalidReinforceLossError",
    "InvalidRolloutError",
    "InvalidTrainerConfigError",
    "LATEST_CHECKPOINT_NAME",
    "MetricsTracker",
    "OnnxParityResult",
    "PolicyDecision",
    "PolicyForward",
    "PongPolicyNetwork",
    "ReinforceUpdateResult",
    "RewardFn",
    "RolloutEpisode",
    "TrainerConfig",
    "TrainingMetrics",
    "TrainingRun",
    "compute_reinforce_loss",
    "compute_batched_rebound_rewards",
    "centering_reward",
    "decide_action",
    "discount_episode_rewards",
    "discount_rewards",
    "export_to_onnx",
    "load_checkpoint",
    "make_policy_callback",
    "normalize_returns",
    "normalized_right_paddle_center_distance",
    "rebound_reward",
    "right_paddle_hit",
    "right_paddle_miss",
    "run_episode",
    "run_reinforce_update",
    "run_training",
    "save_checkpoint",
    "should_apply_centering_bias",
    "verify_onnx_parity",
]
